export const colors = {
    milkyWhite: "#F1EEDD",
    icyWhite: "#F0F4F8",
    white: "white",
    darkOrange: "#FB6801",
    mediumOrange: "#FF822B",
    lightOrange: "#FF8A00",
    darkBlue: "#3B4A9E",
    lightBlue: "#435BBE",
    lighterBlue: "#A8B6F1",
    grey: "rgba(0, 0, 0, 0.5)",
    blurBlack: "rgba(0, 0, 0, 0.3)",
    black: "black",
    pastelDark: "#B3CFBD",
    pastelLight: "#CCDDC7",
    mintDark: "#F4F7FC",
    mintLight: "#E0F7FA",
    darkGreen: "#2FD726",
    lightGreen: "#51E329",
    darkYellow: "#FFD700",
    lightYellow: "#FFEA00",
    darkRed: "#FF0000",
    lightRed: "#FF7F7F",
    lightOcean: "#78EFFF",
    approve: "#2E9724",
    disapprove: "#A63B29",
    blurWhite: "rgba(255,255,255,0.7)",
    superBlurWhite: "rgba(255,255,255,0.02)",
    brown: "#E5C09A",
    centerRibbonLinearLeftTop1: "#FDE07B",
    centerRibbonLinearRightTop1: "#FFCE68",
    leftRibbonLinearLeftTop1: "#F8DD65",
    leftRibbonLinearRightTop1: "#FCAC6F",
    rightRibbonLinearLeftTop1: "#EBA977",
    rightRibbonLinearRightTop1: "#F6C25A",
    centerRibbonLinearLeftTop2: "#FDE07B",
    centerRibbonLinearRightTop2: "#FFCE68",
    leftRibbonLinearLeftTop2: "#F8DD65",
    leftRibbonLinearRightTop2: "#FCAC6F",
    rightRibbonLinearLeftTop2: "#EBA977",
    rightRibbonLinearRightTop2: "#F6C25A",
    centerRibbonLinearLeftTop3: "#FDE07B",
    centerRibbonLinearRightTop3: "#FFCE68",
    leftRibbonLinearLeftTop3: "#F8DD65",
    leftRibbonLinearRightTop3: "#FCAC6F",
    rightRibbonLinearLeftTop3: "#EBA977",
    rightRibbonLinearRightTop3: "#F6C25A",
};